#!/usr/bin/env bash
# will display information about subdomains

func_domain () {
    output=$(dig $2.$1 | grep -A1 "ANSWER SECTION:" | tail -n1)
    ip=$(echo "$output" | cut -f5)
    record=$(echo "$output" | cut -f4)
    echo "The subdomain" "$2" "is a" "$record" "record and points to" "$ip" | awk '{print}'
}

if [ "$#" == 1 ]
then
  func_domain "$1" "www"
  func_domain "$1" "lb-01"
  func_domain "$1" "web-01"
  func_domain "$1" "web-02"
elif [ "$#" == 2 ]
then
  func_domain "$1" "$2"
fi
