#!/usr/bin/env bash
# will display information about subdomains

func_domain () {
    output=$(dig "$2"."$1" | grep -A1 "ANSWER SECTION:" | tail -n1)
    ip=$(echo "$output" | cut -f4)
    record=$(echo "$output" | cut -f3)
    echo $2 $record $ip | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'

}

if [ "$#" == 1 ]
then
  func_domain "$1" "www"
  func_domain "$1" "lb-01"
  func_domain "$1" "web-01"
  func_domain "$1" "web-02"
elif [ "$#" == 2 ]
then
  func_domain "$1" "$2"
fi
