#!/usr/bin/env bash
# A Bash script that configures a new Ubuntu machine to respect
# Install nginx on your web-01 server
# Nginx should be listening on port 80
# When querying Nginx at its root / with a GET request (requesting a page) 
# using curl, it must return a page that contains the string Holberton School

apt-get -y update
apt-get -y install nginx
echo "Holberton School" | tee /var/www/html/index.nginx-debian.html
sudo service nginx restart
