#!/usr/bin/env bash
# Redirection 

apt-get -y update
apt-get -y install nginx

echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html

new_string="\\\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com;\n\t}"
file="/etc/nginx/sites-available/default"

sudo sed -i "22i $new_string" $file
service nginx restart

