#!/usr/bin/env bash
# Install your load balancer
# Configure HAproxy with version equal or greater than 1.5 
# so that it send traffic to web-01 and web-02
# Distribute requests using a roundrobin algorithm
# Make sure that HAproxy can be managed via an init script

# Configuring  HAproxy (load balancer) with version equal to 1.8
sudo apt-get install software-properties-common -y
sudo add-apt-repository ppa:vbernat/haproxy-1.8 -y
sudo apt-get update -y
sudo apt-get install haproxy=1.8.\* -y
backend="backend web-backend\n\tbalance roundrobin\n\tserver 1476-web-01 35.237.57.250:80 check\n\tserver 1476-web-02 34.75.204.221:80 check\n"
frontend="frontend http\n\tbind *:80\n\tmode http\n\tdefault_backend web-backend"
echo -e "$backend" | sudo tee -a /etc/haproxy/haproxy.cfg
echo -e "$frontend" | sudo tee -a /etc/haproxy/haproxy.cfg
echo 'ENABLED=1' >> '/etc/default/haproxy'
service haproxy restart
