#!/usr/bin/env bash
sudo sed -i '21s/.*/\tlisten 80 default_server;/' /etc/nginx/sites-enabled/default
sudo sed -i '22s/.*/\tlisten [::]:80 default_server ipv6only=on;/' /etc/nginx/sites-enabled/default
sleep 2
sudo service nginx restart
