#!/usr/bin/env bash
# find out whatss keeping your container ngnix from listening on port 80
cp /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
sudo pkill ngnix
