#!/usr/bin/env bash
# A Bash (init) script that manages manage_my_process.


case "$1" in
    start)
        ./manage_my_process&
        echo "$$" > /var/run/my_process.pid
        echo "manage_my_process started"
        exit
        ;;
    stop)
        echo "manage_my_process stopped"
        pkill -f "./var/run/my_process.pid"
        rm /var/run/my_process.pid
        exit
        ;;
    restart)
        pkill -f "./var/run/my_process.pid"
        rm /var/run/my_process.pid
        ./manage_my_process&
        echo "$$" > /var/run/my_process.pid
        echo "manage_my_process restarted"
        exit
        ;;
    *)
        echo "Usage: manage_my_process {start|stop|restart}"
        exit
        ;;
esac
exit $?
