#!/usr/bin/env bash
# Bash script that displays the content of the 
# file /etc/passwd, using the while loop + IFS

while IFS= read -r line;
do
      IFS=':'
      read -ra ARR <<< "$line"
      echo "The user ${ARR[0]} is part of the ${ARR[3]} gang, lives in ${ARR[5]} and rides ${ARR[6]}. ${ARR[2]}'s place is protected by the passcode ${ARR[1]}, more info about the user here: ${ARR[4]}" 
done < "/etc/passwd"
