#!/usr/bin/env bash
# Bash script that gives you information about the holbertonschool file.

FILE="holbertonschool"
if [ ! -e "$FILE" ]; then
    echo "$FILE file does not exist"
else
    echo "$FILE file exists"
        if [ -s $FILE ]; then
            echo "$FILE file is not empty"
        else
            echo "$FILE file is empty"
        fi
        if [ -f "$FILE" ]; then
            echo "$FILE is a regular file"
        fi
        
fi

