#!/usr/bin/env bash
#  Run Nginx as Nginx listening on all active IPs on port 8080 
pkill apache2
chmod 004 /etc/nginx/nginx.conf
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
