#!/bin/bash

# A script that configures all dependencies to config a web server for the Project
# AirBnB_clone_v4

# pip3
sudo apt-get install python3-pip -y

# Flask
pip3 install Flask -y
pip3 install flask_cors -y

# Mysql
echo 'deb http://repo.mysql.com/apt/ubuntu/ trusty mysql-5.7-dmr' | sudo tee -a /etc/apt/sources.list

# Mysqldb
sudo apt-get update
sudo apt-get install mysql-server-5.7
sudo apt-get install python3-dev
sudo apt-get install libmysqlclient-dev -y
sudo apt-get install zlib1g-dev
sudo pip3 install mysqlclient==1.3.10

# Installing SQLAlchemy
pip3 install SQLAlchemy==1.2.5

# config database using the script
# cat setup_mysql_dev.sql | mysql -uroot -p (password: root)
cat setup_mysql_dev.sql | mysql -uroot -p erika

#Put information to the database
curl -o 100-dump.sql "https://s3.amazonaws.com/intranet-projects-files/holbertonschool-higher-level_programming+/290/100-hbnb.sql"
cat 100-dump.sql | mysql -uroot -p erika

# Install flasgger documentation for all Flask views
sudo pip3 install flasgger

